### ISSUE TITLE
403 Client Error

### ISSUE THREAD

**Issue by m0rsmordre** [pseudonym117/Riot-Watcher#171]
I'm running a script on VPS. My VPS in France. Isn't it legal?

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/riotwatcher/Handlers/ThrowOnErrorHandler.py", line 18, in after_request
    response.raise_for_status()
  File "/usr/local/lib/python3.6/dist-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://tr1.api.riotgames.com/lol/league/v4/entries/RANKED_SOLO_5x5/IRON/I?page=1

During handling of the above exception, another exception occurred:
```

**Comment by m0rsmordre** [comment]
Issue solved. It's my bad sorry token was expired
