### ISSUE TITLE
_match_list_request NameError

### ISSUE THREAD

**Issue by hijaek** [pseudonym117/Riot-Watcher#44]
matchlist = _match_list_request('XXX')

I am getting this error

Traceback (most recent call last):
  File "C:\Python27\Newer Folder\lolwatcher.py", line 11, in <module>
    matchlist = match_list_request('mufasakim')
NameError: name '_match_list_request' is not defined

**Comment by hijaek** [comment]
matchlist = w.get_match_list('28396810', seasons=4)
print(matchlist)

this gives me

Traceback (most recent call last):
  File "C:\Python27\Newer Folder\lolwatcher.py", line 11, in <module>
    matchlist = w.get_match_list('28396810', seasons=4)
  File "C:\Python27\Newer Folder\RW.py", line 517, in get_match_list
    endIndex=end_index
  File "C:\Python27\Newer Folder\RW.py", line 503, in _match_list_request
    **kwargs
  File "C:\Python27\Newer Folder\RW.py", line 248, in base_request
    raise_status(r)
  File "C:\Python27\Newer Folder\RW.py", line 183, in raise_status
    raise LoLException(error_400, response)
LoLException: Bad request

**Comment by pseudonym117** [comment]
OK there were 2 issues here: 

first one was my fault, the variable name should be 'season' not 'seasons'. that is updated as of 190751a.

second, the 'season' parameter needs to be one of the values listed here https://developer.riotgames.com/api/methods#!/1042/3590 (I hope this hyperlinks right). BUT - there now are constants defined in the riotwatcher file that you can use instead of hardcoding these strings. The one for season 4 would be 'season_2014', for preseason 4 would be 'preseason_2014'.
