### ISSUE TITLE
Error from set_raw_limit

### ISSUE THREAD

**Issue by wc1997** [pseudonym117/Riot-Watcher#83]
Not sure if this is my fault but I got this error when I was trying to grab match data recursively given a list of matchIds. It was run in a simple for loop and included a self rate limit by sleeping after 100 requests. I got this error 2x both around the 10000th recursive call. However running it my third time everything went smoothly.

Traceback (most recent call last):
  File "getMatchDataStats.py", line 42, in <module>
    match = recentMatches(game)
  File "getMatchDataStats.py", line 13, in recentMatches
    return watcher.match.by_id(region, id)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/riotwatcher/_apis/MatchApiV3.py", line 31, in by_id
    '/lol/match/v3/matches/{matchId}'.format(matchId=match_id)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/riotwatcher/_apis/NamedEndpoint.py", line 28, in _request
    return self._base_api.request(self._endpoint_name, method_name, region, url_ext, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/riotwatcher/_apis/BaseApi.py", line 34, in request
    mod = handler.after_request(region, endpoint_name, method_name, url, response)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/riotwatcher/Handlers/RateLimit/RateLimitHandler.py", line 63, in after_request
    limiter.update_limiter(region, endpoint_name, method_name, response)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/riotwatcher/Handlers/RateLimit/HeaderBasedLimiter.py", line 49, in update_limiter
    scoped_limit.update_limits(raw_limits)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/riotwatcher/Handlers/RateLimit/Limits.py", line 33, in update_limits
    self._limits[raw_limit.time].set_raw_limit(raw_limit)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/riotwatcher/Handlers/RateLimit/Limits.py", line 100, in set_raw_limit
    raw_limit.count = self._raw_limit.count
AttributeError: can't set attribute

**Comment by pseudonym117** [comment]
fixed with commit 3ff8418 (says build failed, but issue was just odd behavior of test case. fixed). version 2.2.1 on pypi has fix
